language: python
python:
  - "3.6"

services:
  - postgresql
  
script:
  - psql -U postgres -c 'create database noharm;'
  - psql -U postgres -d noharm -a -f noharm-create.sql -v ON_ERROR_STOP=1
  - psql -U postgres -d noharm -a -f noharm-triggers.sql -v ON_ERROR_STOP=1
  - psql -U postgres -d noharm -a -f noharm-insert.sql -v ON_ERROR_STOP=1
  - pg_dump -U postgres --schema='demo' noharm -s | sed 's/demo/demo_test/g' | psql -U postgres -d noharm -v ON_ERROR_STOP=1
  - psql -U postgres -d noharm -a -f noharm-test.sql -v ON_ERROR_STOP=1
  - psql -U postgres -d noharm -a -f noharm-newuser.sql -v ON_ERROR_STOP=1
  
after_script:
  - git clone https://github.com/noharm-ai/backend/
  - cd backend
  - pip install -q -r requirements.txt
  - python mobile.py &
  - sleep 5
  - curl localhost:5000/patient-name/1234
  - TOKEN=$(curl -X POST -d '{"email":"demo", "password":"demo"}' -H "Content-Type: application/json" localhost:5000/authenticate | jq -r '.access_token')
  - curl -H "Authorization: Bearer ${TOKEN}" localhost:5000/prescriptions/20
