CREATE USER readall WITH PASSWORD 'readall';
GRANT CONNECT ON DATABASE postgres TO readall;

GRANT USAGE ON SCHEMA demo TO readall;
GRANT SELECT ON ALL TABLES IN SCHEMA demo TO readall;

GRANT USAGE ON SCHEMA public TO readall;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readall;

CREATE USER onlydemo WITH PASSWORD 'onlydemo';
GRANT CONNECT ON DATABASE postgres TO onlydemo;
GRANT USAGE ON SCHEMA demo TO onlydemo;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA demo TO onlydemo;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA demo TO onlydemo;
GRANT SELECT ON TABLE demo.usuario TO onlydemo;

CREATE USER api_user WITH PASSWORD 'userapi';
GRANT CONNECT ON DATABASE postgres TO api_user;
GRANT USAGE ON SCHEMA demo, public TO api_user;
GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA public TO api_user;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA demo TO api_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA demo TO api_user;
GRANT DELETE ON demo.segmentosetor TO api_user;
GRANT DELETE ON demo.outlier TO api_user;
