CREATE USER readall WITH PASSWORD 'readall';
GRANT CONNECT ON DATABASE postgres TO readall;

GRANT USAGE ON SCHEMA demo TO readall;
GRANT SELECT ON ALL TABLES IN SCHEMA demo TO readall;

GRANT USAGE ON SCHEMA public TO readall;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readall;


CREATE USER onlydemo WITH PASSWORD 'onlydemo';
GRANT CONNECT ON DATABASE postgres TO onlydemo;

GRANT USAGE ON SCHEMA demo TO onlydemo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA demo TO onlydemo;

GRANT USAGE ON SCHEMA public TO onlydemo;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO onlydemo;